### ISSUE TITLE
Allow OpenMP to be turned on/off by parameter (or better, num_threads specified)

### ISSUE THREAD

**Issue by nippoo** [klusta-team/klustakwik#24]
Setting NumThreads = [value] for example.

**Comment by thesamovar** [comment]
You can use the OMP_NUM_THREADS environment variable already. Maybe this is enough?

**Comment by nippoo** [comment]
Clunky, but will probably do for now! The nice thing with having it as an option is allowing it to be printed to the logfile etc...

**Comment by thesamovar** [comment]
OK, well given that we are rewriting soon, I'll close this issue.
