### ISSUE TITLE
Allow building without OpenMP in OpenMP branch

### ISSUE THREAD

**Issue by thesamovar** [klusta-team/klustakwik#31]
I have tried to fix this in the use_less_ram branch. @nippoo do you have access to a mac that shows this problem? If so, could you test if "make noopenmp" solves the problem? Note that it can be combined with other parameters, e.g. "make debug noopenmp".

**Comment by nippoo** [comment]
Sadly doesn't work:

```
make noopenmp
make: Nothing to be done for `noopenmp'.
```

**Comment by thesamovar** [comment]
Did you make clean first?

**Comment by nippoo** [comment]
Yes I did!

**Comment by thesamovar** [comment]
Weird, OK I'll try again.

**Comment by thesamovar** [comment]
OK, new stragegy. Now do "make NOOPENMP=1" or "make debug NOOPENMP=1".

**Comment by nippoo** [comment]
Works great for me!

**Comment by thesamovar** [comment]
Great, closing this issue.
